---
- name: Deploy Prometheus, Alertmanager, kube-state-metrics, and fetch kubeconfig
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install Helm
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - tar
      tags:
        - helm

    - name: Download and install Helm
      become: true
      shell: |
        wget https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz
        tar -zxvf helm-v3.8.1-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
      tags:
        - helm

    - name: Add Prometheus Helm repository
      become: true
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      tags:
        - helm

    - name: Update Helm repositories
      become: true
      command: helm repo update
      tags:
        - helm

    - name: Create namespace for Prometheus
      become: true
      command: kubectl create namespace prometheus
      ignore_errors: yes

    - name: Deploy Prometheus
      become: true
      command: helm install prometheus prometheus-community/prometheus -n prometheus
      tags:
        - prometheus

    - name: Deploy kube-state-metrics
      become: true
      command: helm install kube-state-metrics prometheus-community/kube-state-metrics -n prometheus
      tags:
        - kube-state-metrics

    - name: Deploy Alertmanager
      become: true
      command: helm install alertmanager prometheus-community/alertmanager -n prometheus
      tags:
        - alertmanager

    - name: Fetch kubeconfig file from master1 and set KUBECONFIG locally
      hosts: master1
      gather_facts: false
      tasks:
        - name: Fetch kubeconfig file
          fetch:
            src: ~/.kube/config
            dest: /tmp/master1_kubeconfig
            flat: yes

    - name: Set KUBECONFIG locally
      hosts: localhost
      gather_facts: false
      environment:
        KUBECONFIG: "./master1_kubeconfig"
      tasks:
        - name: Check Kubernetes cluster info
          command: kubectl cluster-info
