- hosts: masters
  become: true
  vars_files:
    - vault.yaml

  tasks:
    - name: Get kubeconfig from master01
      fetch:
        src: "~/.kube/config"
        dest: "/tmp/master1_kubeconfig"
        flat: yes
      when: inventory_hostname == "master01"

- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars.yaml
    
  tasks:
    - name: Set KUBECONFIG environment variable
      shell: "{{ kubeconfig_task }}"
      args:
        executable: /bin/bash

    - name: Get Kubernetes Nodes
      become: true
      shell: | 
        {{ kubeconfig_task }}
        kubectl get nodes
      

    # - name: Create namespace for monitoring
    #   become: true      
    #   shell: | 
    #     {{ kubeconfig_task }}
    #     kubectl create namespace monitoring
    #   ignore_errors: yes

    # - name: Create namespace for elk
    #   become: true      
    #   shell: | 
    #     {{ kubeconfig_task }}
    #     kubectl create namespace elk
    #   ignore_errors: yes
    
    - name: Create namespace for kubernetes-dashboard
      become: true      
      shell: | 
        {{ kubeconfig_task }}
        kubectl create namespace kubernetes-dashboard
      ignore_errors: yes

    - name: Download Kubernetes Dashboard YAML
      get_url:
        url: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml"
        dest: "/tmp/kubernetes-dashboard.yaml"

    - name: give permissions to kubernetes-dashboard.yaml
      command: |
            chmod +x /tmp/kubernetes-dashboard.yaml

    - name: Replace API server host in YAML file
      shell: |
        sed -i 's|apiserver-host=http://my-address:port|apiserver-host={{apiserver}}|' /tmp/kubernetes-dashboard.yaml
      args:
        executable: /bin/bash

    - name: deploy Kubernetes Dashboard YAML
      shell: | 
        {{ kubeconfig_task }} 
        kubectl apply -f /tmp/kubernetes-dashboard.yaml
      args:
        executable: /bin/bash

      
    # - name: deploy fluentd
    #   shell: | 
    #     {{ kubeconfig_task }} 
    #     kubectl apply -f beeline_fluentd.yaml -n elk
    #   args:
    #     executable: /bin/bash

    # - name: deploy prometheus
    #   shell: | 
    #     {{ kubeconfig_task }} 
    #     kubectl apply -f beeline_prometheus.yaml -n monitoring
    #   args:
    #     executable: /bin/bash

    # - name: deploy metric server
    #   shell: | 
    #     {{ kubeconfig_task }} 
    #     kubectl apply -f beeline_metric_server.yaml -n kube-system
    #   args:
    #     executable: /bin/bash