- hosts: masters
  become: true

  vars_files:
    - vault.yaml

  tasks:
    - name: Fetch kubeconfig from Kubernetes master node
      ansible.builtin.fetch:
        src: ~/.kube/config
        dest: /tmp/master1_kubeconfig
        flat: yes
      delegate_to: localhost

    - name: Print success message
      ansible.builtin.debug:
        msg: "Kubeconfig successfully fetched from the master node and saved locally."
